"""autogenerated by genpy from cgr_localization/DisplayMsg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class DisplayMsg(genpy.Message):
  _md5sum = "20f2e94b57c956606f1d7505b08c9d10"
  _type = "cgr_localization/DisplayMsg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 timestamp

float64 robotLocX
float64 robotLocY
float64 robotAngle

float64 windowSize

float32[] lines_p1x
float32[] lines_p1y
float32[] lines_p2x
float32[] lines_p2y
uint32[]   lines_col

float32[] points_x
float32[] points_y
uint32[]   points_col

float32[] circles_x
float32[] circles_y
uint32[]   circles_col

"""
  __slots__ = ['timestamp','robotLocX','robotLocY','robotAngle','windowSize','lines_p1x','lines_p1y','lines_p2x','lines_p2y','lines_col','points_x','points_y','points_col','circles_x','circles_y','circles_col']
  _slot_types = ['float64','float64','float64','float64','float64','float32[]','float32[]','float32[]','float32[]','uint32[]','float32[]','float32[]','uint32[]','float32[]','float32[]','uint32[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,robotLocX,robotLocY,robotAngle,windowSize,lines_p1x,lines_p1y,lines_p2x,lines_p2y,lines_col,points_x,points_y,points_col,circles_x,circles_y,circles_col

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DisplayMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0.
      if self.robotLocX is None:
        self.robotLocX = 0.
      if self.robotLocY is None:
        self.robotLocY = 0.
      if self.robotAngle is None:
        self.robotAngle = 0.
      if self.windowSize is None:
        self.windowSize = 0.
      if self.lines_p1x is None:
        self.lines_p1x = []
      if self.lines_p1y is None:
        self.lines_p1y = []
      if self.lines_p2x is None:
        self.lines_p2x = []
      if self.lines_p2y is None:
        self.lines_p2y = []
      if self.lines_col is None:
        self.lines_col = []
      if self.points_x is None:
        self.points_x = []
      if self.points_y is None:
        self.points_y = []
      if self.points_col is None:
        self.points_col = []
      if self.circles_x is None:
        self.circles_x = []
      if self.circles_y is None:
        self.circles_y = []
      if self.circles_col is None:
        self.circles_col = []
    else:
      self.timestamp = 0.
      self.robotLocX = 0.
      self.robotLocY = 0.
      self.robotAngle = 0.
      self.windowSize = 0.
      self.lines_p1x = []
      self.lines_p1y = []
      self.lines_p2x = []
      self.lines_p2y = []
      self.lines_col = []
      self.points_x = []
      self.points_y = []
      self.points_col = []
      self.circles_x = []
      self.circles_y = []
      self.circles_col = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_5d.pack(_x.timestamp, _x.robotLocX, _x.robotLocY, _x.robotAngle, _x.windowSize))
      length = len(self.lines_p1x)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.lines_p1x))
      length = len(self.lines_p1y)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.lines_p1y))
      length = len(self.lines_p2x)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.lines_p2x))
      length = len(self.lines_p2y)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.lines_p2y))
      length = len(self.lines_col)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.pack(pattern, *self.lines_col))
      length = len(self.points_x)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.points_x))
      length = len(self.points_y)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.points_y))
      length = len(self.points_col)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.pack(pattern, *self.points_col))
      length = len(self.circles_x)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.circles_x))
      length = len(self.circles_y)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.circles_y))
      length = len(self.circles_col)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.pack(pattern, *self.circles_col))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.timestamp, _x.robotLocX, _x.robotLocY, _x.robotAngle, _x.windowSize,) = _struct_5d.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.lines_p1x = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.lines_p1y = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.lines_p2x = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.lines_p2y = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      end += struct.calcsize(pattern)
      self.lines_col = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.points_x = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.points_y = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      end += struct.calcsize(pattern)
      self.points_col = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.circles_x = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.circles_y = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      end += struct.calcsize(pattern)
      self.circles_col = struct.unpack(pattern, str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_5d.pack(_x.timestamp, _x.robotLocX, _x.robotLocY, _x.robotAngle, _x.windowSize))
      length = len(self.lines_p1x)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.lines_p1x.tostring())
      length = len(self.lines_p1y)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.lines_p1y.tostring())
      length = len(self.lines_p2x)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.lines_p2x.tostring())
      length = len(self.lines_p2y)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.lines_p2y.tostring())
      length = len(self.lines_col)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.lines_col.tostring())
      length = len(self.points_x)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.points_x.tostring())
      length = len(self.points_y)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.points_y.tostring())
      length = len(self.points_col)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.points_col.tostring())
      length = len(self.circles_x)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.circles_x.tostring())
      length = len(self.circles_y)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.circles_y.tostring())
      length = len(self.circles_col)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.circles_col.tostring())
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.timestamp, _x.robotLocX, _x.robotLocY, _x.robotAngle, _x.windowSize,) = _struct_5d.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.lines_p1x = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.lines_p1y = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.lines_p2x = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.lines_p2y = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      end += struct.calcsize(pattern)
      self.lines_col = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.points_x = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.points_y = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      end += struct.calcsize(pattern)
      self.points_col = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.circles_x = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.circles_y = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      end += struct.calcsize(pattern)
      self.circles_col = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_5d = struct.Struct("<5d")
