(cl:defpackage cgr_localization-srv
  (:use )
  (:export
   "LOCALIZATIONINTERFACESRV"
   "<LOCALIZATIONINTERFACESRV-REQUEST>"
   "LOCALIZATIONINTERFACESRV-REQUEST"
   "<LOCALIZATIONINTERFACESRV-RESPONSE>"
   "LOCALIZATIONINTERFACESRV-RESPONSE"
  ))

